### ISSUE TITLE
Handling before/after events

### ISSUE THREAD

**Issue by alloy** [NYTimes/react-tracking#42]
First of all, this solution looks excellent ✨  At Artsy we were in the process of designing a similar solution, but happy to stop that effort in favour of using yours (both in React and React Native).

One thing that we did include in our design and yours doesn’t seem to have, but please correct me if I overlooked it, is the possibility to send before/after events when the decorated function performs e.g. an API call. Our design for this was that _if_ the decorated function returns a `Promise` we’d tap into that and fire the tracking function both before and after (possibly with error) the promise finishes.

Would you accept a PR for that? If so, we’ll start using your lib and start porting our code over to yours.

**Comment by tizmagik** [comment]
Hey that sounds very interesting, I hadn't thought of that!

Would be happy to accept a PR, but I'd like to understand the use cases a bit first. Also, are you aware of any trade offs that'd need to be made with this added functionality?

**Comment by mennenia** [comment]
Hi @tizmagik! Thanks for getting back to us.

The use case involves a function that can either succeed or fail, for example when a user logs in or create an account. 

We capture the fact that the user tried to log in (tapped a button), and then a separate track event on whether they managed or not.

When that request fails, it could be for a variety of reasons, e.g. wrong email/password combo, and we log this within the same event, so we have the context, rather than relying on something like the fact that the next page being loaded (e.g. a `pageView` event) means that log in succeeded.

This could look like there being three sets of `trackingData` and `options`, the base action, and two for when the decorated function success or fails (which could be captured if the function returns a `Promise`). Naturally, only two of the three ‘tracks’ will be sent. 

As for tradeoffs, I’m not entirely sure at this point in time. 

Naturally, we don’t want every promise function to have to specify this type of tracking, but I think that can easily be circumvented (e.g. the approach of omitting data implying nothing will be sent is already demonstrated in your [`options.process` docs](https://github.com/NYTimes/react-tracking#top-level-optionsprocess)). 

What are your thoughts? Do you foresee any issues or complications? 

Thanks for your time!

**Comment by tizmagik** [comment]
Hi @mennenia ! Thanks for providing this context, this is helpful.

To be clear, I wouldn't be against adding the ability for react-tracking to be able to handle decorating functions that return Promises. I'd be more than happy to review a PR. My concern would be just that it shouldn't add any unnecessary burden/overhead to how it's used today (in which react-tracking has no knowledge about what the decorated function does).

But also, I would encourage to think about how the existing API could be leveraged to do what I think you're trying to do. Here's a naive implementation showing some untested code that I think achieves what you're looking to do without adding any new complexity to react-tracking.

```js
import React, { Component } from 'react';
import track from 'react-tracking';
import Loading from '../Loading'; // some Loading component
import userApi from '../userApi'; // some Promise-based User API

// this decorator not only establishes page tracking context, 
// but also makes props.tracking.trackEvent() available
@track({
  page: 'sign-in'
})
export default class SignIn extends Component {

  state = {
    attemptingSignIn: false,
  }

  // note, this doesn't have to be used as a decorator
  // you could just call props.tracking.trackEvent() within handleSignIn()
  // before the API call to track the 'sign-in-attempt' event
  @track((props, [event]) => ({
    event: 'sign-in-attempt',
    user: event.target.username.value
  }))
  handleSignIn = (event) => {
    event.preventDefault();

    // update some state to show a spinner, etc.
    this.setState({
      attemptingSignIn: true,
    });

    // grab submitted data
    const username = event.target.username.value;
    const password = event.target.password.value;
    
    // Attempt sign in via Promise-based API call
    userApi.signIn({ username, password })
      .then(result => {

        // track sign-in success
        this.props.tracking.trackEvent({
          event: 'sign-in-success',
          username,
        });
        
        // now re-route to relevant page
        window.location.href = "/myaccount" // or soft-nav
      })
      .catch(error => {
        // track sign in failure
        this.props.tracking.trackEvent({
          event: 'sign-in-failed',
          username,
        });
        
        // now re-route to error page (e.g. "/account-help")
        window.location.href = "/account-help" // or soft-nav
      })
  }
  
  render() {
    return this.state.attemptingSignIn
      ? <Loading />
      : <form onSubmit={this.handleSignIn}>
          <input type="text" name="username" />
          <input type="password" name="password" />
          <button type="submit">Submit</button>
        </form>;
  }
}
```

Would love to hear what you think and even expand on this a bit more if I've missed something, or there's some challenges on your end where the pattern shown above is not possible.

Cheers!

**Comment by mennenia** [comment]
Thanks for such a detailed response (and code example)!

This approach is definitely possible, and much in line with a traditional analytics implementation where you can send events as the code performs the actions. 

The reason we were hoping to avoid this is that we'd love to separate analytics tracking code from app code dictating behaviour and logic. This is one of the reasons we were looking at decorators, and why react-tracking looks great! Furthermore, our goal was for analytics to be declarative, rather than imperative, much like React and Relay's principles.

It's great to know that you'd be open to receiving feature PRs. I completely hear you about not wanting react-tracking to have knowledge about the function it's applied to, and especially not adding overhead to how it's currently used. 

For now, I think we'll go ahead and get started with react-tracking and as we isolate the cases where we'd like this type of 'before/after' analytics, we can submit a PR (aiming to be in line with your project goals!) for further discussion at that point.

Thanks again for your time!

**Comment by alloy** [comment]
Thanks for the write-ups @mennenia and for the thoughtful responses @tizmagik!

I’ll close this 👍

**Comment by tizmagik** [comment]
Thanks folks -- just to close the loop here.

> The reason we were hoping to avoid this is that we'd love to separate analytics tracking code from app code dictating behaviour and logic. This is one of the reasons we were looking at decorators, and why react-tracking looks great! Furthermore, our goal was for analytics to be declarative, rather than imperative, much like React and Relay's principles.

That's fair, another approach you might take which is a bit less imperative is to break out the `.then` and `.catch` blocks into separate functions and decorate those:

```js
...

  @track({ event: 'sign-in-successful' })
  handleSuccess = () => { ... }

  @track({ event: 'sign-in-failed' })
  handleFailure = () => { ... }

  @track({ event: 'sign-in-attempt' })
  handleSignIn = (event) => {
    userApi.signIn({ username, password })
      .then(handleSuccess)
      .catch(handleFailure);
  }

...
```

Cheers
