### ISSUE TITLE
Expose decorated component

### ISSUE THREAD

**Issue by BRKalow** [NYTimes/react-tracking#70]
We're evaluating using this within our application and a talking point came up on testing components that are decorated with `track`. It would be great to have access to the decorated component so it can be tested without having to mock `track`.

`react-dnd` has a pretty cool pattern for this, exposing a `DecoratedComponent` static property: http://react-dnd.github.io/react-dnd/docs-testing.html (source: https://github.com/react-dnd/react-dnd/tree/master/packages/react-dnd/src/decorateHandler.tsx#L39). 

If your team has any insight into how you test components decorated with `track`, I'm all ears.

Alternatively, if you would be open to an approach similar to `react-dnd` for exposing the decorated component, I'd be willing to open a PR for that!

Thanks for the library!

**Comment by tizmagik** [comment]
Hey @BRKalow great question!

If you're using Jest, I would recommend just mocking `react-tracking` globally. We do this in our codebase via Jest configuration:

```js
/* jest.config.js */
module.exports = {
  moduleNameMapper: {
    '^react-tracking$': path.resolve(__dirname, '__mocks__/react-tracking.js')
  },
};
```

```js
/* __mocks__/react-tracking.js */
module.exports = () => c => c;
```

This way in your tests you don't have to worry about calling `jest.mock('react-tracking')` (it's done globally) and from the test perspective the decorator isn't even there (the mock passes through to the decorated component), so no need to even grab the reference from the `DecoratedComponent` property.

I would personally prefer this approach over adding a static `DecoratedComponent` property, but I'm open to hearing what problems that would solve that the global mocking pattern doesn't!

On the other hand, if that mocking approach works for you would love a PR to the README since this question has come up a couple times. Cheers! 😁

**Comment by BRKalow** [comment]
This is the approach I was considering, and I think the right one in the end.

As far as testing any non-trivial logic that may exist in a decorator, which is what led me down this path, I think one would be better off defining that logic outside of the decorator and testing it in isolation.

Borrowing your example from the Advanced Usage section of the README:
```js
// if this function gets complex, consider externalizing it so it can be unit-tested.
@track((props) => {
  return { page: props.isNew ? 'new' : 'existing' }
})
export default class FooButton extends React.Component {
```
Just thinking out loud. 😄


I'd be happy to open up a PR to address the topic of testing in the README, closing the issue now as I think we've come to a conclusion. Thanks for the quick reply!
